//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ljekarna.Database___Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lijek()
        {
            this.DetaljiNarudžbe = new HashSet<DetaljiNarudžbe>();
            this.DetaljiRačuna = new HashSet<DetaljiRačuna>();
            this.Nekompatibilni_Lijekovi = new HashSet<Nekompatibilni_Lijekovi>();
            this.Nekompatibilni_Lijekovi1 = new HashSet<Nekompatibilni_Lijekovi>();
        }
    
        public int LijekID { get; set; }
        public string Naziv { get; set; }
        public string Proizvođač { get; set; }
        public double Cijena { get; set; }
        public int Oblik { get; set; }
        public bool NaRecept { get; set; }
        public int NaStanju { get; set; }
        public int MinimalnaKoličina { get; set; }
        public double NabavnaCijena { get; set; }
        public string Tip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaljiNarudžbe> DetaljiNarudžbe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaljiRačuna> DetaljiRačuna { get; set; }
        public virtual Proizvođač Proizvođač1 { get; set; }
        public virtual Tipovi Tipovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nekompatibilni_Lijekovi> Nekompatibilni_Lijekovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nekompatibilni_Lijekovi> Nekompatibilni_Lijekovi1 { get; set; }
    }
}
