//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ljekarna.Database___Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljač> Dobavljač { get; set; }
        public virtual DbSet<Kupac> Kupac { get; set; }
        public virtual DbSet<Lijek> Lijek { get; set; }
        public virtual DbSet<Narudžba> Narudžba { get; set; }
        public virtual DbSet<Proizvođač> Proizvođač { get; set; }
        public virtual DbSet<Račun> Račun { get; set; }
        public virtual DbSet<UlogaZaposlenika> UlogaZaposlenika { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
        public virtual DbSet<DetaljiNarudžbe> DetaljiNarudžbe { get; set; }
        public virtual DbSet<DetaljiRačuna> DetaljiRačuna { get; set; }
        public virtual DbSet<Tipovi> Tipovi { get; set; }
        public virtual DbSet<Nekompatibilni_Lijekovi> Nekompatibilni_Lijekovi { get; set; }
    }
}
