//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ljekarna.Database___Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nekompatibilni_Lijekovi
    {
        public int ID { get; set; }
        public int Lijek_ID_1 { get; set; }
        public int Lijek_ID_2 { get; set; }
    
        public virtual Lijek Lijek { get; set; }
        public virtual Lijek Lijek1 { get; set; }
    }
}
