//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ljekarna.Database___Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvođač
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvođač()
        {
            this.Lijek = new HashSet<Lijek>();
        }
    
        public int ProizvođačID { get; set; }
        public string Proizvođač1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lijek> Lijek { get; set; }
    }
}
