//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ljekarna.Database___Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Račun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Račun()
        {
            this.DetaljiRačuna = new HashSet<DetaljiRačuna>();
        }
    
        public int RačunID { get; set; }
        public int KupacID { get; set; }
        public int ZaposlenikID { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Kupac Kupac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaljiRačuna> DetaljiRačuna { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
